spring:
  application:
    name: spring-batch

  batch:
    job:
      enabled: true
      name: example3Job2
    jdbc:
      initialize-schema: always

  # H2 Database
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:mem:test'
    username: username
    password: password

  # H2 Console
  h2:
    console:
      enabled: true
      path: /h2-console

  # JPA
  jpa:
    hibernate:
      ddl-auto: validate # flyway가 실행되고 ddl-auto가 실행됨. validate로 설정하여 검증 모드로 설정.
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false
    defer-datasource-initialization: false  # hibernate와 flyway 초기화 실행 순서 지정. false로 설정하면 flyway가 먼저 실행됨.

  # Flyway
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db
    baseline-version: 0
    fail-on-missing-locations: true

mybatis:
  mapper-locations: "classpath:/mapper/*.xml"