spring:
  application:
    name: spring-batch

  batch:
    job:
      enabled: true
      name: example2Job1
    jdbc:
      initialize-schema: always

  # H2 Database
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:mem:test'
    username: username
    password: password

  # H2 Console
  h2:
    console:
      enabled: true
      path: /h2-console

  # JPA
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        show_sql: false
    open-in-view: false